version: "3.9"
services:
  web:
    image: docker.tangerie.xyz/testimage:latest
    ports:
      - "8123:8123"
    deploy:
      mode: global
      placement:
        constraints: [node.labels.CAMERA == true]
networks:
  app:
    driver: overlay