version: "3.9"
services:
  web:
    image: docker.tangerie.xyz/testimage:latest
    ports:
      - "8123:8123"
    deploy:
      mode: global
      placement:
        constraints: [node.labels.CAMERA == true]
    volumes:
      - /dev/v4l/by-id/usb-Sonix_Technology_Co.__Ltd._USB_2.0_Camera_SN0001-video-index0:/dev/video0
    environment:
      - PUID="UID"
      - PGID="GID"
    privileged: true
networks:
  app:
    driver: overlay