version: "3.9"
services:
  web:
    image: docker.tangerie.xyz/testimage:latest
    ports:
      - "8123:8123"
    deploy:
      mode: global
      placement:
        constraints: [node.labels.CAMERA == true]
    volumes:
      - /dev:/dev
    environment:
      - PUID="UID"
      - PGID="GID"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
networks:
  app:
    driver: overlay